// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pigwwyckhwkseombflul.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBpZ3d3eWNraHdrc2VvbWJmbHVsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc0Njg0MDMsImV4cCI6MjA3MzA0NDQwM30._z1suCgYZn7NEI39hJTswPDfyalD1kXNYKZZS0Hl4rs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});